docs_dir: docs
site_name: JEAN SUMMET


theme:
  logo: assets/Logo_agro.png
  font:
    text: Montserrat
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.path
    

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: lime
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: lime
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/git-alt

nav:
- Home: index.md 
- Goals Question Metrics - Fase definição: goalsQuestionMetrics.md