docs_dir: docs
site_name: JEAN SAMMET
repo_url: https://github.com/FCTE-Qualidade-de-Software-1/2025-1-T02-JEAN-SAMMET
repo_name: 2025.1-JEAN SAMMET

theme:
  name: material
  logo: assets/jean-sammet.png 
  favicon: assets/jean-sammet.png
  font:
    text: Montserrat
    code: Roboto Mono

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: light-green
      toggle:
        icon: material/weather-night
        name: Mudar para modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: light-green
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo claro
  icon:
    repo: fontawesome/brands/github

nav:
- Início: index.md 
- Fase 1: slides.md
- Goals Question Metrics - Fase definição: goalsQuestionMetrics.md